### ISSUE TITLE
centos:7 image on ppc64le shows me that it is Centos8

### ISSUE THREAD

**Issue by smuzaffar** [CentOS/sig-cloud-instance-images#175]
I am trying to rebuild our docker container based on latest centos:7 image for ppc64le. Somehow the library/centos:7 container for ppc64le tell me that it is based on centos8 [a]. Any ida what am I doing wrong here?

[a]
```
> uname -a
Linux xyz.hostname 3.10.0-957.21.3.el7.ppc64le #1 SMP Tue Jun 18 16:48:04 UTC 2019 ppc64le ppc64le ppc64le GNU/Linux
> cat /etc/redhat-release
CentOS Linux release 7.6.1810 (AltArch)
> docker pull library/centos:7
7: Pulling from library/centos
Digest: sha256:8b65474bd89ef48e04c21db31d1b283558b114f7d34a001cdbaed747bc4dbd16
Status: Image is up to date for centos:7
> docker run --rm library/centos:7 cat /etc/redhat-release
CentOS Linux release 8.2.2004 (Core)
> singularity -s exec docker://library/centos:7 cat /etc/redhat-release
CentOS Linux release 8.2.2004 (Core)
```

**Comment by smuzaffar** [comment]
@bstinsonmhk , @jperrin  , can you please look in to this?

**Comment by mrodozov** [comment]
eventually figured it out. I can hard code our latest image for some time

**Comment by bstinsonmhk** [comment]
I have a fix for this, will push to the library shortly.

**Comment by smuzaffar** [comment]
any update?

**Comment by bstinsonmhk** [comment]
Can you try pulling again? We should have the fix merged in dockerhub.

**Comment by smuzaffar** [comment]
I tried but I am still getting the old image. Looks like docker hub does not contain your updates ( https://hub.docker.com/_/centos?tab=tags&page=1&ordering=last_updated ) . Tags there are still 4 days old. OR am I looking in to wroing docker hub repository?

**Comment by smuzaffar** [comment]
thanks, this is now fixed
```
>docker pull library/centos:7
7: Pulling from library/centos
3fe478aaff9b: Pull complete
Digest: sha256:0f4ec88e21daf75124b8a9e5ca03c37a5e937e0e108a255d890492430789b60e
Status: Downloaded newer image for centos:7
>docker run --rm library/centos:7 cat /etc/redhat-release
CentOS Linux release 7.9.2009 (AltArch)

```
