### ISSUE TITLE
systemd conflicts with file from package systemd-container

### ISSUE THREAD

**Issue by fogfish** [CentOS/sig-cloud-instance-images#19]
Hello,

It seems that recent systemd-container changes broke the latest images.
I used to have in my app Dockerfile

RUN \
   yum -y install       \
      librsvg2-tools    \
      librsvg2-tools    \
      dejavu-sans-fonts \
      dejavu-serif-fonts

The image build is broken with following error:

Transaction check error:
  file /usr/lib64/libsystemd-daemon.so.0.0.10 from install of systemd-libs-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-libs-208.20-4.el7.centos.x86_64
  file /usr/lib64/libsystemd-id128.so.0.0.26 from install of systemd-libs-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-libs-208.20-4.el7.centos.x86_64
  file /usr/lib64/libsystemd-journal.so.0.11.3 from install of systemd-libs-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-libs-208.20-4.el7.centos.x86_64
  file /usr/lib64/libsystemd-login.so.0.9.1 from install of systemd-libs-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-libs-208.20-4.el7.centos.x86_64
  file /usr/lib64/libudev.so.1.4.0 from install of systemd-libs-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-libs-208.20-4.el7.centos.x86_64
  file /usr/lib64/security/pam_systemd.so from install of systemd-libs-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-libs-208.20-4.el7.centos.x86_64
  file /etc/rc.d/rc.local from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/journalctl from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/localectl from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/loginctl from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/systemctl from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/systemd-ask-password from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/systemd-cat from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/systemd-coredumpctl from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/systemd-detect-virt from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/systemd-inhibit from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/systemd-machine-id-setup from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/systemd-notify from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/systemd-run from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/systemd-tmpfiles from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/systemd-tty-ask-password-agent from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/bin/udevadm from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/system-generators/systemd-rc-local-generator from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-ac-power from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-activate from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-binfmt from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-cgroups-agent from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-coredump from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-fsck from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-initctl from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-journald from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-localed from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-logind from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-multi-seat-x from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-random-seed from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-remount-fs from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-reply-password from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-shutdown from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-shutdownd from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-sleep from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-sysctl from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-udevd from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-update-utmp from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-user-sessions from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/systemd/systemd-vconsole-setup from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/udev/accelerometer from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/udev/ata_id from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/udev/cdrom_id from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/udev/collect from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/udev/mtd_probe from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/udev/scsi_id from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64
  file /usr/lib/udev/v4l_id from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-4.el7.centos.x86_64

**Comment by jperrin** [comment]
I can duplicate this here. It appears that libgudev1-208-20 is including the release string in its dep requirement which is causing this.

**Comment by jperrin** [comment]
This is a bug upstream with RH's systemd-container. I've submitted the report, so you can follow along if you wish via  -> https://bugzilla.redhat.com/show_bug.cgi?id=1209640. In the meantime. I'm going to build a centos specific version of the package and update the container in the index.

**Comment by jperrin** [comment]
Okay. got a fix for this that should be coming in the next day or so.

**Comment by jperrin** [comment]
resolved with https://github.com/docker-library/official-images/pull/652 whenever that gets merged in.

**Comment by fogfish** [comment]
Thank you!

**Comment by raykrueger** [comment]
It looks like all the dependencies are out there but I'm still seeing an issue.
With the following Dockerfile

```
FROM centos:centos7
RUN yum -y install epel-release && yum -y update
RUN yum -y install salt-master
```

```
docker pull centos:centos7
docker build .
```

Results in...

```
  file /usr/lib64/libsystemd-login.so.0.9.1 from install of systemd-libs-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/libudev.so.1.4.0 from install of systemd-libs-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /usr/lib64/security/pam_systemd.so from install of systemd-libs-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-libs-208.20-6.el7.centos.x86_64
  file /etc/rc.d/rc.local from install of systemd-208-20.el7_1.2.x86_64 conflicts with file from package systemd-container-208.20-6.el7.centos.x86_64
```

And much more.

**Comment by jperrin** [comment]
@raykrueger salt is pulling in systemd-python, which isn't provided by systemd-container. In this instance, you're probably better off using yum-swap to either replace systemd-container with _actual_ systemd or the fakesystemd package from http://dev.centos.org/centos/7/fakesystemd/

I'll push on the upstream folks for a better fix, but these are likely to be your two best options in the short term.

**Comment by jperrin** [comment]
@raykrueger okay. I've addressed the issue with systemd-container, and I'll be submitting a new pull request for the container into the docker index shortly.

**Comment by raykrueger** [comment]
Thanks @jperrin that's fantastic!

**Comment by jperrin** [comment]
@raykrueger  https://github.com/docker-library/official-images/pull/662 so, whenever that gets merged in...

**Comment by raykrueger** [comment]
Just wanted to finally follow up and say thanks :) This works perfectly now.
