### ISSUE TITLE
Docker i686 image broken

### ISSUE THREAD

**Issue by TheAssassin** [CentOS/sig-cloud-instance-images#94]
I've recently discovered https://hub.docker.com/r/i386/centos/, specifically the tag `6`. I tried to use it, but there's a bunch of issues. `yum` seems to try to install 64-bit packages, which is a problem for obvious reasons. Other tools, like e.g., `uname`, also return `x86_64`.

It'd be great if that could be fixed, as a third party image we're using at the moment (https://hub.docker.com/r/toopher/centos-i386/) hasn't been updated for years, and also has quite some issues, mainly being incompatible to `centos:6` package wise and otherwise, too.

Furthermore, it'd be great if you could choose different tags, like with `library/centos`, such as `6.8`, `6.9`.

JFYI: I'm primarily interested in `i386/centos:6`.

At the moment, the published image is just not working, which is a bad sign. I hope you can fix it soon.

**Comment by jperrin** [comment]
uname will return x86_64 because the kernel comes from the host. tools that key off host values like this will have to be manually changed to use x86 vs x86_64 directly.

**Comment by TheAssassin** [comment]
I thought of that to be an issue, too. Though, tools like `yum` should be made install the 32-bit tools. I don't know `yum` very much, does it rely on `uname` etc. in some way to figure out the architecture?

Build scripts etc. relying on `uname` won't work either naturally. But that's more of a layer 8 issue I guess.

**Comment by jperrin** [comment]
Yum does indeed rely on the architecture to determine the repo path.

You'd want to edit `/etc/yum.repos.d/CentOS-Base.repo` and change $basearch to i386 to force it to pull from the proper path.

**Comment by TheAssassin** [comment]
Can this be done upstream, i.e., in this repository, too, please?

I'll try to quick-fix that with sed in my build script, and will report issues if I find more of them here.

**Comment by TheAssassin** [comment]
So far I can tell that after fixing the `yum` configuration, it works well usability wise.

Check it out: https://github.com/TheAssassin/AppImageBuild

By the way, in [the other image I linked to](https://hub.docker.com/r/toopher/centos-i386/), `uname` behaves as expected, and returns `i686`. I'd ask you to consider changing it to this value in this image as well. I don't know how e.g., the `debian` image behaves here, but I guess they're returning `x86_64` as well, so I don't know whether changing would be a good idea.

**Comment by hfierros** [comment]
A simpler solution... on x86_64 architectures add: **RUN echo "i386" > /var/yum/variables/basearch** to your Dockerfile.

**Comment by TheAssassin** [comment]
@hfierros to me it seems more useful to change the `$basearch` variable, which might be used by other tools, too.

**Comment by ghost** [comment]
@TheAssassin what is your use case to run i386 containers on a x86_64 host?

**Comment by mcauto** [comment]
you can check 'getconf LONG_BIT`.
if container 32bit, print 32 
if container 64bit, print 64

**Comment by TheAssassin** [comment]
@bobcanthelpyou we're using it here: https://github.com/AppImage/AppImageBuild/blob/master/Dockerfile.i386

**Comment by jperrin** [comment]
try a fresh image. this should be fixed iirc.

**Comment by ghost** [comment]
@jperrin this is not fixed for `i386/centos:6`, you talking about the CentOS 7 Image?

**Comment by AlexFalappa** [comment]
@hfierros according to [Red Hat Enterprise Linux 6 official documentation](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/deployment_guide/sec-using_yum_variables) yum variables should be in `/etc/yum/vars/` instead of `/var/yum/variables/`.

The correct command that worked for me is:
```
RUN echo "i386" > /etc/yum/vars/basearch
```

**Comment by TheAssassin** [comment]
@AlexFalappa that instruction should be run in the upstream image, the user should not have to include that in their Dockerfile.

**Comment by jperrin** [comment]
yeah, I fixed it for the centos7 image. the c6 fix was just merged yesterday with https://github.com/CentOS/sig-cloud-instance-build/pull/138

**Comment by AlexFalappa** [comment]
When will the updated image be made available on hub.docker.com or registry.centos.org ?

**Comment by haplabs** [comment]
just install docker.io and ok

**Comment by freakanonymous** [comment]
all of this still isnt working with centos six. you basically gotta reinstall your OS sadly.

and doing it remotely on centos 6 is near impossible, even gcc is broken on centos.

**Comment by jperrin** [comment]
CentOS 6 is end-of-life, so there won't be any changes there.
